# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dymensional
tagline:          'Open Source 3D Printers'
description:      'A website to showcase the open-source 3D Printer projects developed by Aaron Bislip.'
url:              http://www.dymensional.com
baseurl:          /

author:
  name:           'Dymensional'
  url:            'dymensional.nl'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Dymensional

# Exclude these files from  production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
